export type Shapes = {
    id: string,
    roomId: string,
    userId: string,
    type: "RECTANGLE",
    x: number,
    y: number,
    width: number,
    height: number,
    color?: string,
} | {
    id: string,
    roomId: string,
    userId: string,
    type: "CIRCLE",
    x: number, 
    y: number, 
    radiusX: number,
    radiusY: number,
    color?: string,
} | {
    id: string,
    roomId: string,
    userId: string,
    type: "LINE",
    x: number, 
    y: number, 
    points: {
        endX: number,
        endY: number
    },
    color?: string,
} | {
    id: string,
    roomId: string,
    userId: string,
    type: "ARROW",
    x: number, 
    y: number, 
    points: {
        endX: number,
        endY: number
    },
    color?: string,
} | {
    id: string,
    roomId: string,
    userId: string,
    type: "PENCIL",
    points: Array<{x: number, y: number}>,
    color?: string,
} | {
    id: string,
    roomId: string,
    userId: string,
    type: "TEXT",
    textContent: string,
    x: number,
    y: number,
    points: Array<{letter: string}>,
    color?: string,
} | {
    id: string,
    roomId: string,
    userId: string,
    type: "ERASER",
    points: Array<{x: number, y: number}>,
    color?: string,
}