name: Deploy to production

on:
  push:
    branches: [ main ]

jobs:
  redeploy:
    runs-on: ubuntu-latest
    name: Deploying everything to production
    steps:
      - name: Deploy using SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.29.29.85 >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no michaelhosamani26@34.29.29.85 -t "cd CollaboDraw/ && git pull origin main && source ~/.nvm/nvm.sh && nvm install v22.12.0 && nvm use v22.12.0 && npm install -g pnpm@9.15.1 && pnpm install && pnpm run build && pm2 restart all"